[package]
name = "nyx-dashboard"
version = "1.0.0"
description = "Nyx Dashboard"
authors = ["Jérôme ODIER"]
license = "GPL"
repository = "https://gitlab.in2p3.fr/lpsc-kid/nyx-dashboard"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "nyxdashboard_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
tauri = { version = "2.0.4", features = ["devtools"] }
tauri-plugin-notification = "2.0.1"
tauri-plugin-dialog = "2.0.1"
tauri-plugin-shell = "2.0.1"
tauri-plugin-store = "2.0.1"
tauri-plugin-http = { version = "2.0.1", features = ["blocking"] }
tauri-plugin-fs = "2.0.1"
base64 = "0.22.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
warp = "0.3.7"
