image: ubuntu:jammy

before_script:
    - apt-get update
    - apt-get install -y file wget curl
    - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -

    - apt-get install -y make rustc cargo nodejs pkg-config
    - apt-get install -y libssl-dev libgtk-3-dev librsvg2-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev libjavascriptcoregtk-6.0-dev

    - npm --version
    - node --version
    - rustc --version
    - cargo --version

stages:
    - build

build_project:
    stage: build
    script:
        - npm install
        - npm run tauri-prod

        - mv src-tauri/target/release/bundle/appimage/nyx-dashboard_*.AppImage ./nyx-dashboard.AppImage
    artifacts:
        paths:
            - ./nyx-dashboard.AppImage
        expire_in: 1 week
        when: always
    only:
        - main
